### ISSUE TITLE
Easier integration with ASP.NET pipeline

### ISSUE THREAD

**Issue by DarinMacRae** [stormpath/stormpath-sdk-dotnet#118]
The SDK has done a good job at keeping concerns separated. However, given the prevalence certain frameworks like ASP.NET it would be convenient if there was a library of adapters for easily (and quickly) integrating in StormPath. 

For instance, given the need to authenticate a request in ASP.NET a developer should only need to write something like this:

```
public class AuthenticationHandler : DelegatingHandler
{
    protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    {
        ...
        application.AuthenticateAccountAsync(request, cancellationToken); // less ceremony
        ...
    }
}
```

This would come by pulling in Stormpath.SDK.AspDotNet or something like that.

**Comment by nbarbettini** [comment]
This is coming! It will indeed be part of a different package to keep the concerns separated.

Right now, the closest the SDK gets to this is the `HttpRequests` helper class that allows you to convert a framework request into an `IHttpRequest`. But this needs to be expanded to support things like ASP.NET (and the specific authentication flow you're doing above) super easily.

I'll update any progress on this issue.

**Comment by fekberg** [comment]
@nbarbettini Do you have any examples on how to set this up with ASP.NET (MVC/WebAPI/DNX)?

**Comment by nbarbettini** [comment]
@fekberg No public examples yet, but I'm working on it. Shoot an email to support@stormpath.com and I can get you some examples tailored to what you need.

**Comment by nbarbettini** [comment]
The MVP of the new Stormpath ASP.NET Core integration is live! https://github.com/stormpath/stormpath-aspnetcore

Quick 'n dirty example: https://github.com/stormpath/stormpath-aspnetcore-example

This should make it significantly easier to use Stormpath with ASP.NET Core 1.0 applications. [ASP.NET 4.x support](https://github.com/stormpath/stormpath-dotnet-owin-middleware/issues/4) is coming soon. And there's a lot more goodies coming down the pike. :smile: 

I'm going to close this issue, but feel free to open issues related to ASP.NET Core [here](https://github.com/stormpath/stormpath-aspnetcore/issues).
