### ISSUE TITLE
Caching returns stale values

### ISSUE THREAD

**Issue by DarinMacRae** [stormpath/stormpath-sdk-dotnet#120]
Imagine that you want to read some custom data values so you make a call like this:
```
    var customData = await subscriberAccount.GetCustomDataAsync(cancellationToken);
```

and then you update that value directly via the Stormpath Admin UI. Then next calls will return the old value. I didn't wait for any length of time to see if they would eventually expire but restarting the process (since I'm using in-memory cache provider) certainly did the trick.

That won't be convenient or in some cases even possible in a production scenario.

**Comment by nbarbettini** [comment]
This is the caching layer working correctly, although it may not be doing what you want.

The default in-memory cache provider has a default TTL (time to live) and TTI (time to idle) of **1 hour**. Your application has no way of knowing that the value was updated directly in the Admin UI (if it did, it'd be an omniscient cache :smile: ).

There are two things you can do:

1. Disable caching entirely by calling `SetCacheProvider(Caches.NewDisabledCacheProvider())` when constructing the `IClient`.
2. Configure lower TTL and TTI values that make sense for your application:
```
clientBuilder.SetCacheProvider(
    Caches.NewInMemoryCacheProvider()
        .WithDefaultTimeToLive(TimeSpan.FromMinutes(10))
        .WithDefaultTimeToIdle(TimeSpan.FromMinutes(5))
        .Build());
```

Cache TTL and TTI can even be customized on a per-resource-type basis, if that level of granularity is needed.

**Comment by nbarbettini** [comment]
FYI, if the resource is updated by the *application*, the local cache is updated (as you would expect).

**Comment by DarinMacRae** [comment]
Agreed on all counts. I threw this out there in case you were using HTTP cache control headers and/or If-Modified-Since\If-None-Match.

I've also seen SignalR be a good candidate for cache invalidation.

We definitely want caching but the values may be updated by an admin using the UI. This is expected to be a rare thing though.

Can you please supply an example of per-resource configuration of TTL/TTI?

**Comment by nbarbettini** [comment]
Indeed - it might be interesting for the client to "subscribe" to updates from the API in a reactive way, but that would require some deep integration from the API side. It's not something on our roadmap right now (to my knowledge).

Generally, keeping the TTL low should make cache misses due to externally-updated data really rare.

There's an example for per-resource configuration buried in the API documentation for [ICacheProviderBuilder.WithCache](http://docs.stormpath.com/dotnet/api/html/M_Stormpath_SDK_Cache_ICacheProviderBuilder_WithCache.htm):

```csharp
var cacheProvider = Caches.NewInMemoryCacheProvider()
    .WithCache(Caches
        .ForResource<Account.IAccount>()
        .WithTimeToLive(TimeSpan.FromHours(2))
        .WithTimeToIdle(TimeSpan.FromHours(2)))
    .Build();
```

The default TTL/TTI set with `WithDefaultTimeTo...` will apply to any resources that aren't overridden by calling `WithCache`.

**Comment by nbarbettini** [comment]
Circling back around on this. @DarinMacRae, did you get a solution that worked for you?

**Comment by DarinMacRae** [comment]
We haven't been working on this. I expect that we will use short TTLs when the time comes.

**Comment by DarinMacRae** [comment]
BTW, when I mentioned SignalR (or Web sockets in general) I meant that your SDK could use it for cache invalidation, not clients.

**Comment by nbarbettini** [comment]
@DarinMacRae Gotcha. I can definitely see how that would work. (For now, it's not on the roadmap.)

I'll go ahead and close this issue - feel free to open another if you have more caching questions.
