### ISSUE TITLE
Expose href on IAuthenticationResult

### ISSUE THREAD

**Issue by dalelotts** [stormpath/stormpath-sdk-dotnet#134]
I really only need the href, it is there in the response but there is no property on IAuthenticationResult to get to it so I am forced to make an unnecessary call to get account.

**Comment by nbarbettini** [comment]
So you need the Account's href, but don't need any other account details?

**Comment by dalelotts** [comment]
Yes, that is correct.

**Comment by nbarbettini** [comment]
Fixed in dec7ae4 :smile:

**Comment by dalelotts** [comment]
Thanks!
