### ISSUE TITLE
AuthenticateAccountAsync throws error instead of returning login result

### ISSUE THREAD

**Issue by lostrouter** [stormpath/stormpath-sdk-dotnet#135]
Calling AuthenticateAccountAsync with a bad username/password combination throws a ResourceError.  Should return a IAuthenticationResult with Success as false.

**Comment by nbarbettini** [comment]
I agree, this is a little confusing. Use TryAuthenticateAccountAsync if you
want a Boolean result. If you need to be able to get the account details,
use AuthenticateAccountAsync and catch the ResourceException.

**Comment by nbarbettini** [comment]
@lostrouter Were you able to get this figured out?

**Comment by lostrouter** [comment]
for now i am following your advice of catching the exception.  are there plans to make use of the success field for failed auth in the future?

**Comment by nbarbettini** [comment]
No, actually I will most likely be removing the Success field so it's less confusing.

Catching the exception is preferred because the `ResourceException` object will contain detailed information about why the failure occurred.
