### ISSUE TITLE
How to restrict account operations to a specific Organization?

### ISSUE THREAD

**Issue by dalelotts** [stormpath/stormpath-sdk-dotnet#136]
When working in a multi-tenant application it would be ideal to just work with IOrganization for authentication, resetting passwords, etc.

At a minimum, being able to authenticate to an IOrganization simplifies most of the implementation.

**Comment by nbarbettini** [comment]
Thanks for the suggestion! I'll see how this fits into our roadmap and ping you back when it's assigned to a milestone.

**Comment by dalelotts** [comment]
Great, I'll also do my best to you a PR for this.

**Comment by nbarbettini** [comment]
After review, I won't be able to add this after all.

Actions like authentication and password reset must always go through an Application (see [How Login Attempts Work in Stormpath](https://docs.stormpath.com/rest/product-guide/latest/auth_n.html#how-login-attempts-work-in-stormpath)). The Application might have multiple account stores assigned (Organizations, Directories, Groups), and Stormpath handles the process of attempting to authenticate against each one (in order) and so on.

An Organization is fundamentally only a "bucket" for accounts. If authentication behavior was added to `IOrganization`, it would muddy the relationship between Applications and account stores.

If you have any questions on this, let me know!

**Comment by dalelotts** [comment]
In a multi-tenant application, authenticating only on the IOrganization is exactly what one would want. Unless I am misunderstanding, the behavior of searching through all of the buckets trying to authenticate has the potential of authenticating a user in the incorrect organization.

For example, user johndoe can have an account with the same username and password in two organizations  (A and D) - he wants to authenticate to organization D - the current API is suboptimal for this use case.

**Comment by dalelotts** [comment]
https://docs.stormpath.com/rest/product-guide/latest/multitenancy.html#what-is-a-multi-tenant-application

**Comment by nbarbettini** [comment]
You're right - unless it's restricted to a specific organization, it will attempt to authenticate against any of them.

I understand your use case better now! When building an authentication request, you can restrict the searching to only a specific account store, or organization `nameKey`. This would solve your problem I believe:

``` csharp
var request = new UsernamePasswordRequestBuilder();
request.SetUsernameOrEmail("johndoe");
request.SetPassword("secretpassword123!");
request.SetAccountStore("orgD"); // can also be an Account Store href

var result = await application.AuthenticateAccountAsync(request.Build());
```

**Comment by dalelotts** [comment]
That is true for authentication, but not for all account related operations.

**Comment by nbarbettini** [comment]
The `SendPasswordResetEmailAsync` method has an [overload](http://docs.stormpath.com/dotnet/api/html/M_Stormpath_SDK_Application_IApplication_SendPasswordResetEmailAsync_1.htm) which takes an account store `href` or organization `nameKey` as well.

What other account operations are you missing?

**Comment by dalelotts** [comment]
I'll look though in more detail and let you know ASAP

**Comment by nbarbettini** [comment]
No problem. I want to make sure the API and documentation are clear for all these use cases. If you find anything, I'll fix as soon as I can.

**Comment by nbarbettini** [comment]
@dalelotts Circling back around on this - any update?

**Comment by dalelotts** [comment]
Ah, sorry, I dropped the ball on this.  

I've moved on, but @jwynia can let you know their current needs.

**Comment by nbarbettini** [comment]
No worries. :smile: 

I'll go ahead and close this issue. @jwynia if you have further requests, open up a fresh one!
