### ISSUE TITLE
Relax the access of ResourceException to be protected internal

### ISSUE THREAD

**Issue by dalelotts** [stormpath/stormpath-sdk-dotnet#140]
When writing unit tests that make use of this SDK there is a need to create new instances of ResourceException, currently that is not possible because the constructor is internal.

**Comment by nbarbettini** [comment]
Can you give an example of a test that would need this?

**Comment by dalelotts** [comment]
A unit test for validating that the registration process handled duplicate registration attempts correctly. i.e. User has already registered successfully, but attempts to register again - a ResourceException will be thrown with the specific code stating the problem - the mock object cannot throw a resource exception.

**Comment by dalelotts** [comment]
A public constructor would be ideal - I don't really want to create a subclass but I will if I have to.

**Comment by nbarbettini** [comment]
Makes sense. I actually already made this change to the constructor signature in my local development branch:

```
public ResourceException(IError error)
```

Would that work well enough for your case?

**Comment by dalelotts** [comment]
Yeah, that will work. Thanks.

**Comment by nbarbettini** [comment]
Change is live in the `dnx` branch: https://github.com/stormpath/stormpath-sdk-dotnet/blob/dnx/src/Stormpath.SDK.Abstractions/Error/ResourceException.cs

**Comment by dalelotts** [comment]
Thanks!

**Comment by nbarbettini** [comment]
Merged!
