### ISSUE TITLE
Typeloader getpath() fails

### ISSUE THREAD

**Issue by hworang** [stormpath/stormpath-sdk-dotnet#142]
Hi,

I am looking at your .net sdk and am running some standard code to create a IClient object, however I am getting some issues within the TypeLoader class as no path can be found within the GetPath() method.  I have installed the sdk via nuget and am running dnx beta8 on windows 10.

It looks like there is an issue with where you are assuming the the file Stormpath.SDK.JsonNetSerializer.dll is stored as the current domain base directory is not where the file is.  the code is using the base directory which in my case is "C:\Users\xxx.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta8\bin\" , however the dll is stored in "C:\Users\xxx.dnx\packages\Stormpath.SDK.JsonNetSerializer\0.5.0\lib".

Am I missing something here or is this a bug?

**Comment by nbarbettini** [comment]
This indeed a bug: #93 

The TypeLoader stuff will be deprecated soon. The workaround (which will be the official syntax in a future version) is this:

```
IClient client = Clients.Builder()
    .SetHttpClient(HttpClients.Create().RestSharpClient())
    .SetSerializer(Serializers.Create().JsonNetSerializer())
    // ...
    .Build();
```

**Comment by nbarbettini** [comment]
If you have any other problems running on dnx, please open more issues! I'm currently doing a lot of retooling work so that it supports both `dnx451` and `dnxcore50`. Happy to get more eyes on it. :smile:
