### ISSUE TITLE
GetAccounts() fails to retrieve IAccount for email containing + symbol

### ISSUE THREAD

**Issue by dnvnjstc** [stormpath/stormpath-sdk-dotnet#175]
It seem that if an email address contains a plus (+) symbol, the call to GetAccounts will fail. Using a temporary email generator such as SharkLasers.com, it will generate an email that will look something like 3rffe4+563camfsbgx34@sharklasers.com.  Using this email, Stormpath is able to create the account via Id Site. This following call will fail to retrieve the IAccount:

> var email = "3rffe4+563camfsbgx34@sharklasers.com";
> var account = await application.GetAccounts().Where(x => x.Username == email).SingleAsync();

with the error:

> "HTTP 401, Stormpath 401 (http://www.stormpath.com/docs/quickstart/connect): Authentication with a valid API Key is required."

...but will successfully retrieve the IAccount for emails with normal syntax.

**Comment by nbarbettini** [comment]
Hi @dnvnjstc, thanks for reporting this! I'll get it fixed in the next release for sure. 👍

**Comment by nbarbettini** [comment]
This bug has been fixed and will go out with v0.9. FYI @dnvnjstc, if you [switch](http://docs.stormpath.com/dotnet/api/html/M_Stormpath_SDK_Client_IClientBuilder_SetAuthenticationScheme.htm) to Basic authentication for now, it'll work. This workaround won't be necessary once v0.9 is live.
