### ISSUE TITLE
ETag and Last-Modified properties

### ISSUE THREAD

**Issue by DarinMacRae** [stormpath/stormpath-sdk-dotnet#194]
Background: When developing a REST API it's common to return an entity along with Etag and Last-Modified headers to support caching and optimistic concurrency.

I am using Stormpath accounts as the backing entity for, say a User resource. Since the definitive definition (true source) of the entity is the account at Stormpath I need to be able to get it's version (Etag) and it's last-modified property. I see that the password has a last modified but the entity can be changed in other ways. 

Can you please expose these properties (you can call them whatever you want) so that they can be forwarded?

**Comment by nbarbettini** [comment]
The Stormpath API doesn't currently have an ETag-like property, but Accounts (and many other resources) do have a `modifiedAt` property. It's exposed in the .NET SDK as the [ModifiedAt](https://docs.stormpath.com/dotnet/api/html/P_Stormpath_SDK_Resource_IAuditable_ModifiedAt.htm) property.

Feel free to log a request at http://ideas.stormpath.com/ for ETag support! It'd have to be added to the API before it can show up in the SDK.

**Comment by DarinMacRae** [comment]
Just curious, how does Stormpath support optimistic concurrency without something like an ETag?

I'm asking so that I can log the correct request.

**Comment by omgitstom** [comment]
Hi @DarinMacRae,

I'm head of product @ Stormpath.  I think this is a very good request and is something that I've wanted to add to the API.  The way that I've seen customers manage this today is in their application code or microservice that updates accounts. 

I've logged this in the ideas portal here:
http://ideas.stormpath.com/ideas/IAM-I-102

Feel free to upvote and provide any additional details.  Thanks!
Tom

**Comment by DarinMacRae** [comment]
Hi @omgitstom ,

Thanks. I understand that this can be done somewhat effectively in app code but as you know the Admin UI allows for direct access so this would make any non-definitive versioning ineffective.

We'll work with the modifiedAt property for now.

BTW, the idea you linked to doesn't appear to exist.

Cheers,

Darin
