### ISSUE TITLE
Exception thrown when accessing Status property on IAccount of Facebook user retrieved via IApplication.GetAccountAsync()

### ISSUE THREAD

**Issue by brianrak** [stormpath/stormpath-sdk-dotnet#215]
Accessing the Status property on an instance of IAccount that points to a Facebook user throws the following Exception: 

```
Unable to cast object of type 'System.String' to type 'Stormpath.SDK.Account.AccountStatus'.
```

The stack trace is:

```
at Stormpath.SDK.Impl.Resource.AbstractResource.GetProperty[T](String name)
at Stormpath.SDK.Impl.Account.DefaultAccount.Stormpath.SDK.Account.IAccount.get_Status()
at [MyClass].<MyMethod>d__4.MoveNext() in [MyCode].cs:line 142
```

Interestingly, if, prior to accessing the Status property, you use IApplication.GetAccounts() to get the same account, and then try to access the Status property on the original instance of IAccount, the Exception is no longer thrown.

Here is a method that demonstrates the behavior. (The parameter `token` is a Facebook user token retrieved in the usual way.)

```
private async Task GitHubRepro(IClient client, IApplication application, string token)
{
    var request = client.Providers().Facebook().Account().SetAccessToken(token).Build();
    var result = await application.GetAccountAsync(request).ConfigureAwait(false);

    try
    {
        // Exception thrown here
        var status = result.Account.Status;
    }
    catch (Exception e)
    {
        Console.WriteLine("Exception unexpectedly thrown: {0}\r\n{1}", e.Message, e.StackTrace);
    }

    // The presense of this line allows the Status property to work properly
    var throwaway = await application.GetAccounts().Where(a => a.Username == result.Account.Username).ToListAsync().ConfigureAwait(false);

    // Same property on same object, no exception this time.
    var statusTake2 = result.Account.Status;

    Console.WriteLine("Success after getting the account once in a different way.");
}
```

**Comment by nbarbettini** [comment]
Thanks for the detailed report @brianrak. I'll take a look and update here.

**Comment by nbarbettini** [comment]
Hey @brianrak - does this still occur in version [0.95.0](https://www.nuget.org/packages/Stormpath.SDK/0.95.0) or better? We made some improvements to how these fields are being parsed.

If not, let me know and I'll circle back around on this again. Thanks for your patience!

**Comment by brianrak** [comment]
@nbarbettini After updating to 0.95.0, this no longer repros. I'll close the bug. Thank you for the help!

**Comment by nbarbettini** [comment]
Fantastic! Thanks for your patience and for following up @brianrak. Cheers!
