### ISSUE TITLE
Nuget GAC error when installing Stormpath.SDK.Cache.Redis

### ISSUE THREAD

**Issue by jolovin** [stormpath/stormpath-sdk-dotnet#244]
During installation of the Redis package, I receive the following error:

`PM> Install-Package Stormpath.SDK.Cache.Redis -version 0.95.0

Attempting to gather dependency information for package 'Stormpath.SDK.Cache.Redis.0.95.0' with respect to project 'MountvilleWebAPI', targeting '.NETFramework,Version=v4.5'
Gathering dependency information took 2.68 sec
Attempting to resolve dependencies for package 'Stormpath.SDK.Cache.Redis.0.95.0' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Stormpath.SDK.Cache.Redis.0.95.0'
Resolved actions to install package 'Stormpath.SDK.Cache.Redis.0.95.0'
Retrieving package 'Stormpath.SDK.Cache.Redis 0.95.0' from 'nuget.org'.
Retrieving package 'StackExchange.Redis 1.1.608' from 'nuget.org'.
Adding package 'StackExchange.Redis.1.1.608' to folder 'C:\Development\mountvilleWebAPI\MountvilleWebAPI\packages'
Added package 'StackExchange.Redis.1.1.608' to folder 'C:\Development\mountvilleWebAPI\MountvilleWebAPI\packages'
Added package 'StackExchange.Redis.1.1.608' to 'packages.config'
Successfully installed 'StackExchange.Redis 1.1.608' to MountvilleWebAPI
Adding package 'Stormpath.SDK.Cache.Redis.0.95.0' to folder 'C:\Development\mountvilleWebAPI\MountvilleWebAPI\packages'
Added package 'Stormpath.SDK.Cache.Redis.0.95.0' to folder 'C:\Development\mountvilleWebAPI\MountvilleWebAPI\packages'
Install failed. Rolling back...
Package 'Stormpath.SDK.Cache.Redis.0.95.0 : Newtonsoft.Json [9.0.1, ), StackExchange.Redis [1.1.608, ), Stormpath.SDK.Abstractions [0.95.0, )' does not exist in project 'MountvilleWebAPI'
Removed package 'StackExchange.Redis.1.1.608' from 'packages.config'
Removing package 'Stormpath.SDK.Cache.Redis.0.95.0 : Newtonsoft.Json [9.0.1, ), StackExchange.Redis [1.1.608, ), Stormpath.SDK.Abstractions [0.95.0, )' from folder 'C:\Development\mountvilleWebAPI\MountvilleWebAPI\packages'
Removed package 'Stormpath.SDK.Cache.Redis.0.95.0 : Newtonsoft.Json [9.0.1, ), StackExchange.Redis [1.1.608, ), Stormpath.SDK.Abstractions [0.95.0, )' from folder 'C:\Development\mountvilleWebAPI\MountvilleWebAPI\packages'
Removing package 'StackExchange.Redis.1.1.608' from folder 'C:\Development\mountvilleWebAPI\MountvilleWebAPI\packages'
Removed package 'StackExchange.Redis.1.1.608' from folder 'C:\Development\mountvilleWebAPI\MountvilleWebAPI\packages'
Executing nuget actions took 2.98 sec
**Install-Package : Failed to add reference. The package 'Stormpath.SDK.Cache.Redis' tried to add a framework reference to 'System.Threading.Tasks' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.**
At line:1 char:1
+ Install-Package Stormpath.SDK.Cache.Redis -version 0.95.0
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Time Elapsed: 00:00:05.7105035`

Visual Studio version: 2015 Update 3
Project type: ASP.NET 4.5

**Comment by nbarbettini** [comment]
I think this is the same as https://github.com/stormpath/stormpath-sdk-dotnet/issues/213. Should be a simple fix based on https://github.com/aspnet/Home/issues/1157. I'll make sure this makes it into the next release. 👍
