### ISSUE TITLE
ID Site MFA

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-sdk-dotnet#253]
```{require_mfa: [‘sms’]}``` https://stormpath.atlassian.net/wiki/display/AM/ID+Site+Multifactor

**Comment by nbarbettini** [comment]
FYI: the workaround you can use today is:

```csharp
idSiteBuilder.SetClaim("require_mfa", new[] { "sms" });
```

Once this issue is fixed, the syntax will be simpler:

```csharp
// in the next version
idSiteBuilder.SetRequireMfa("sms", "google_authenticator");
```
