### ISSUE TITLE
Rename repository from csharp to dotnet

### ISSUE THREAD

**Issue by typerandom** [stormpath/stormpath-sdk-dotnet#49]
This SDK can be used by any language that runs on the CLR but the repository name gives the impression that there is only support for C#. Therefore, wouldn't it be better to rename it from `stormpath-sdk-csharp` to `stormpath-sdk-dotnet`?

**Comment by omgitstom** [comment]
I'm fine with this, but we need to make sure that we put C# in the readme somewhere so that people searching for C# vs .net can find this repo
