### ISSUE TITLE
Token-based authentication

### ISSUE THREAD

**Issue by nbarbettini** [stormpath/stormpath-sdk-dotnet#62]
- [x] OAuthPolicy
- [x] Password Grant
- [x] Refresh Grant

https://docs.stormpath.com/guides/token-management/

**Comment by jmoring** [comment]
+1
I assume this will include generation, validation, refresh and revoke of tokens?
Where does this fit on your priority list?

Good job!
Thanks

**Comment by nbarbettini** [comment]
That's the plan. Trying to make it as easy as possible!

Currently, the priority on this is after [milestone 0.3](https://github.com/stormpath/stormpath-sdk-dotnet/milestones/0.3.0).

**Comment by nbarbettini** [comment]
Closed via #95.

@jmoring Coming very shortly in v0.4. :smile:
