### ISSUE TITLE
How do I use the SDK to validate an access token?

### ISSUE THREAD

**Issue by lostrouter** [stormpath/stormpath-sdk-dotnet#97]
I have an application where I want to use tokens, and validate them on the incoming request.  I cannot find the documentation for this feature.

**Comment by nbarbettini** [comment]
HI @lostrouter - token generation and validation is coming in release 0.4, see #62. 

Just checking - is the incoming access token you need to validate one that was previously generated by Stormpath? Until [v0.4](https://github.com/stormpath/stormpath-sdk-dotnet/milestones/0.4.0) is released (very soon!), you can make a manual call to the API:

```
GET https://api.stormpath.com/v1/applications/{APPLICATION_ID}/authTokens/{FULL_JWT_STRING}
```

I created [a gist](https://gist.github.com/nbarbettini/19c886e9b517ad669953) which demonstrates how to do this with RestSharp. See [this section](http://docs.stormpath.com/guides/token-management/#validating-access-tokens) of our Token Auth guide for more details.

**Comment by lostrouter** [comment]
@nbarbettini The token i am validating is from Stormpath.  Thanks for the gist.
